package monkeyscode

import (
	"fmt"
	"strings"
	"time"
)

// ExportOptions configures export behavior.
type ExportOptions struct {
	Title            string
	IncludeToolCalls bool
	IncludeFileDiffs bool
	IncludeCost      bool
}

// DefaultExportOptions returns sensible defaults.
func DefaultExportOptions() ExportOptions {
	return ExportOptions{
		Title:            "MonkeysCode Agent Report",
		IncludeToolCalls: true,
		IncludeFileDiffs: true,
		IncludeCost:      true,
	}
}

// Transcript is a structured export of an agent result.
type Transcript struct {
	Version    string           `json:"version"`
	ExportedAt string           `json:"exportedAt"`
	Result     TranscriptResult `json:"result"`
}

// TranscriptResult is the result section of a transcript.
type TranscriptResult struct {
	Success      bool         `json:"success"`
	Status       string       `json:"status"`
	Summary      string       `json:"summary"`
	Model        string       `json:"model"`
	Cost         float64      `json:"cost"`
	DurationMs   int64        `json:"durationMs"`
	Tokens       TokenUsage   `json:"tokens"`
	FilesChanged []FileChange `json:"filesChanged"`
}

// ToMarkdown converts an agent result to a Markdown report.
func ToMarkdown(result *Result, opts ...ExportOptions) string {
	o := DefaultExportOptions()
	if len(opts) > 0 {
		o = opts[0]
	}

	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s\n\n", o.Title))

	// Summary
	b.WriteString("## Summary\n\n")
	status := "✅ Success"
	if !result.Success {
		status = "❌ Failed"
	}
	b.WriteString(fmt.Sprintf("- **Status**: %s\n", status))
	b.WriteString(fmt.Sprintf("- **Model**: %s\n", result.Model))
	if result.SessionID != "" {
		b.WriteString(fmt.Sprintf("- **Session**: `%s`\n", result.SessionID))
	}
	if result.DurationMs > 0 {
		b.WriteString(fmt.Sprintf("- **Duration**: %s\n", formatDuration(float64(result.DurationMs))))
	}
	b.WriteString("\n")

	// Agent output
	if result.Summary != "" {
		b.WriteString("## Agent Output\n\n")
		b.WriteString(result.Summary)
		b.WriteString("\n\n")
	}

	// Error
	if result.Error != "" {
		b.WriteString("## Error\n\n")
		b.WriteString(fmt.Sprintf("> %s\n\n", result.Error))
	}

	// Files changed
	if len(result.FilesChanged) > 0 && o.IncludeFileDiffs {
		b.WriteString("## Files Changed\n\n")
		b.WriteString(fmt.Sprintf("%d file(s) modified:\n\n", len(result.FilesChanged)))
		for _, f := range result.FilesChanged {
			b.WriteString(fmt.Sprintf("- `%s` (%s)\n", f.Path, f.Action))
			if f.Diff != "" {
				b.WriteString("\n```diff\n")
				b.WriteString(f.Diff)
				b.WriteString("\n```\n\n")
			}
		}
	}

	// Cost
	if o.IncludeCost {
		b.WriteString("## Cost & Usage\n\n")
		b.WriteString("| Metric | Value |\n")
		b.WriteString("|--------|-------|\n")
		b.WriteString(fmt.Sprintf("| Cost | $%.4f |\n", result.Cost))
		b.WriteString(fmt.Sprintf("| Input tokens | %d |\n", result.Tokens.Input))
		b.WriteString(fmt.Sprintf("| Output tokens | %d |\n", result.Tokens.Output))
		if result.Tokens.Thinking > 0 {
			b.WriteString(fmt.Sprintf("| Thinking tokens | %d |\n", result.Tokens.Thinking))
		}
		b.WriteString(fmt.Sprintf("| Total tokens | %d |\n", result.Tokens.Total))
		b.WriteString("\n")
	}

	// Footer
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by MonkeysCode SDK at %s*\n", time.Now().UTC().Format(time.RFC3339)))

	return b.String()
}

// ToHTML converts an agent result to a styled HTML report.
func ToHTML(result *Result, opts ...ExportOptions) string {
	md := ToMarkdown(result, opts...)
	title := "MonkeysCode Agent Report"
	if len(opts) > 0 && opts[0].Title != "" {
		title = opts[0].Title
	}

	// Minimal MD→HTML
	body := markdownToHTML(md)

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s</title>
<style>
:root {
  --bg: #0d1117;
  --fg: #e6edf3;
  --accent: #58a6ff;
  --success: #3fb950;
  --error: #f85149;
  --border: #30363d;
  --code-bg: #161b22;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--bg);
  color: var(--fg);
  max-width: 860px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
  line-height: 1.6;
}
h1 { border-bottom: 1px solid var(--border); padding-bottom: 0.5em; color: var(--accent); }
h2 { margin-top: 2em; }
code { background: var(--code-bg); padding: 0.2em 0.4em; border-radius: 4px; font-size: 0.9em; }
pre { background: var(--code-bg); padding: 1em; border-radius: 8px; overflow-x: auto; }
pre code { background: none; padding: 0; }
table { width: 100%%; border-collapse: collapse; margin: 1em 0; }
th, td { padding: 0.5em 0.75em; text-align: left; border: 1px solid var(--border); }
th { background: var(--code-bg); }
blockquote { border-left: 3px solid var(--error); padding-left: 1em; color: var(--error); }
hr { border: none; border-top: 1px solid var(--border); margin: 2em 0; }
em { color: #8b949e; }
</style>
</head>
<body>
%s
</body>
</html>`, title, body)
}

// ToTranscript creates a structured JSON-serializable transcript.
func ToTranscript(result *Result) *Transcript {
	fc := make([]FileChange, len(result.FilesChanged))
	copy(fc, result.FilesChanged)

	return &Transcript{
		Version:    "1.0",
		ExportedAt: time.Now().UTC().Format(time.RFC3339),
		Result: TranscriptResult{
			Success:      result.Success,
			Status:       result.Status,
			Summary:      result.Summary,
			Model:        result.Model,
			Cost:         result.Cost,
			DurationMs:   result.DurationMs,
			Tokens:       result.Tokens,
			FilesChanged: fc,
		},
	}
}

// markdownToHTML does minimal markdown conversion (headings, lists, code, tables).
func markdownToHTML(md string) string {
	lines := strings.Split(md, "\n")
	var out strings.Builder
	inCode := false

	for _, line := range lines {
		if strings.HasPrefix(line, "```") {
			if inCode {
				out.WriteString("</code></pre>\n")
				inCode = false
			} else {
				out.WriteString("<pre><code>")
				inCode = true
			}
			continue
		}
		if inCode {
			out.WriteString(escapeHTML(line))
			out.WriteString("\n")
			continue
		}

		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if trimmed == "---" {
			out.WriteString("<hr>\n")
			continue
		}

		// Headings
		if strings.HasPrefix(trimmed, "# ") {
			out.WriteString(fmt.Sprintf("<h1>%s</h1>\n", trimmed[2:]))
		} else if strings.HasPrefix(trimmed, "## ") {
			out.WriteString(fmt.Sprintf("<h2>%s</h2>\n", trimmed[3:]))
		} else if strings.HasPrefix(trimmed, "### ") {
			out.WriteString(fmt.Sprintf("<h3>%s</h3>\n", trimmed[4:]))
		} else if strings.HasPrefix(trimmed, "- ") {
			out.WriteString(fmt.Sprintf("<li>%s</li>\n", inlineMarkdown(trimmed[2:])))
		} else if strings.HasPrefix(trimmed, "> ") {
			out.WriteString(fmt.Sprintf("<blockquote>%s</blockquote>\n", inlineMarkdown(trimmed[2:])))
		} else if strings.HasPrefix(trimmed, "|") {
			if strings.Contains(trimmed, "---") {
				continue
			}
			cells := strings.Split(trimmed, "|")
			out.WriteString("<tr>")
			for _, c := range cells {
				c = strings.TrimSpace(c)
				if c != "" {
					out.WriteString(fmt.Sprintf("<td>%s</td>", inlineMarkdown(c)))
				}
			}
			out.WriteString("</tr>\n")
		} else if strings.HasPrefix(trimmed, "*") && strings.HasSuffix(trimmed, "*") {
			out.WriteString(fmt.Sprintf("<em>%s</em>\n", trimmed[1:len(trimmed)-1]))
		} else {
			out.WriteString(fmt.Sprintf("<p>%s</p>\n", inlineMarkdown(line)))
		}
	}

	if inCode {
		out.WriteString("</code></pre>\n")
	}

	return out.String()
}

func inlineMarkdown(text string) string {
	text = escapeHTML(text)
	// Bold
	for strings.Contains(text, "**") {
		i := strings.Index(text, "**")
		j := strings.Index(text[i+2:], "**")
		if j < 0 {
			break
		}
		j += i + 2
		text = text[:i] + "<strong>" + text[i+2:j] + "</strong>" + text[j+2:]
	}
	// Inline code
	for strings.Contains(text, "`") {
		i := strings.Index(text, "`")
		j := strings.Index(text[i+1:], "`")
		if j < 0 {
			break
		}
		j += i + 1
		text = text[:i] + "<code>" + text[i+1:j] + "</code>" + text[j+1:]
	}
	return text
}

func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
